Modifications interface page parc
florian987/captain-coaster pull request #29
Opened 2021-12-05 19:21 UTC by shARPII

- Modification du display des coasters pour coller au display des coasters sur la page ranking
- Liens cliquables qui redirige vers ranking avec sélection de filtre
- Liste des parcs proche (moins de 300km & coaster > 80%)
- Lien vers map qui s'ouvre directement sur le parc

2021-12-11 22:25 UTC, shARPII commented
Je te laisse me dire sur ce PR si l'affichage te convient ou s'il y aurait des modifications à apporter, j'ai essayé de reprendre un peu l'interface dans Ranking en augmentant un peu la taille et renseignant des informations en plus (qui ne me semble pas utile dans la page Ranking par contre?)

2021-12-15 12:39 UTC, florian987 commented
> Je te laisse me dire sur ce PR si l'affichage te convient ou s'il y aurait des modifications à apporter, j'ai essayé de reprendre un peu l'interface dans Ranking en augmentant un peu la taille et renseignant des informations en plus (qui ne me semble pas utile dans la page Ranking par contre?)

Je t'ai fait plusieurs retours, tu peux y jeter un oeil ?

2021-12-15 14:33 UTC, florian987 requested changes

2021-12-15 17:18 UTC, shARPII commented on src/Controller/MapsController.php
> +            $park = $this->getDoctrine()->getRepository(Park::class)->findBy(['slug' => $slug]);
Ok

2021-12-15 17:18 UTC, shARPII commented on src/Controller/MapsController.php
> +                'lat' => $lat,
J'ai refactoré cette partie, il y en a plus besoin.

2021-12-15 17:21 UTC, shARPII commented on templates/Maps/index.html.twig
>      function setMarkers(map, markers) {
J'ai simplifié la logique du js.
Juste un point sur le shouldFocus : il ne sert jute à faire un focus sur la fenêtre mais ça ne centre pas la map, je dois quand même garder la partie du setCenter.

2021-12-15 17:30 UTC, shARPII commented
J'ai mis à jour avec le dernier commit.
Au cas où je te met à quoi ressemble le nouveau format, si ça te convient ou non en terme d'affichage des infos.

https://pics.sharpopopo.tk/YasU7/WalEzeyi20.png/raw
https://pics.sharpopopo.tk/YasU7/puyAzoXi03.png/raw

2021-12-16 16:16 UTC, florian987 approved these changes
Top, merci !

2021-12-16 16:17 UTC, merged